Repository persiancal/jcal, pull requests merged in 2025-03, with the labels that each got.

#15 Replace leap year algorithm with the list of leap years
  sources/libjalali/jalali.c
Labels: bug

#9 Feat/add cicd
  .github/workflows/build.yml
  README.md
  sources/autogen.sh
Labels: enhancement

#18 Support out-of-tree build to keep source tree clean of build artifacts
  sources/src/Makefile.am
  sources/test_kit/jalali/Makefile.am
  sources/test_kit/jtime/Makefile.am
Labels: enhancement, discussion-needed
